        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4>Vložení nové odpovědi na problém "<?php echo($problem['nazev']); ?>"</h4>
          <form method="post" action="./">
            <input type="hidden" name="idp" value="<?php echo($this->post_get('idp')); ?>" />
            <div class="form-group">
              <label for="ksid">Kognitivní schéma:</label>
              <select class="form-control" id="ksid" name="ksid">
              <?php
                foreach($kschemas as $kschema)
                {
                  echo("                  <option value=\"".$kschema['id']."\" >".$kschema['nazev']."</option>\n");
                }
              ?>
            </select>
            </div> 
            <div class="form-group">
              <label for="nazev">Odpověď:</label>
              <textarea class="form-control" rows="5" id="nazev" name="nazev"></textarea>
            </div>
            <button type="submit" name="odpovedi" class="btn btn-default" value="Uložit">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
