      <td id="pravy_panel">
        <h4>Editace odpovědi na problém "<?php echo($answer[0]['nazev']); ?>"</h4>
        <form method="post" action="./">
            <input type="hidden" name="idp" value="<?php echo($this->post_get('idp')); ?>" />
            <table>
              <tr><td>Kognitivní schéma:</td><td><select name="idks">
                <?php
                  foreach($kschemas as $kschema)
                  {
                    if ($kschema['id'] == $this->post_get('idks')) { echo("                  <option value=\"".$kschema['id']."\" selected=\"selected\" >".$kschema['nazev']."</option>\n"); }
                    else { echo("                  <option value=\"".$kschema['id']."\" >".$kschema['nazev']."</option>\n"); }
                  }
                ?>
              </select></td></tr>
              <tr><td>Odpověď:</td><td><textarea  name="nazev" cols="100" rows="10" wrap="soft" ><?php echo($answer[0]['odpoved']); ?></textarea></td></tr>
              <tr><td colspan="2" align="center"><input type="submit" name="odpovedi" value="Uložit" /></td></tr>
            </table>
        </form>
      </td><!-- /pravy_panel -->
