     <td id="pravy_panel">
       <h4>Vložení nové odpovědi na problém "<?php echo($problem['nazev']); ?>"</h4>
         <form method="post" action="./"><table>
           <input type="hidden" name="idp" value="<?php echo($this->post_get('idp')); ?>" />
                <tr><td>kognitivní schéma:</td><td><select name="ksid">
                  <?php
                    foreach($kschemas as $kschema)
                    {
                      echo("                  <option value=\"".$kschema['id']."\" >".$kschema['nazev']."</option>\n");
                    }
                  ?>
                </select></td></tr>
           <tr><td>Odpověď:</td><td><textarea  name="nazev" cols="100" rows="10" wrap="soft" /></textarea></td></tr>
           <td colspan="2" align="center"><input type="submit" name="odpovedi" value="Uložit" /></td>
         </table></form>
