        <div class="col-sm-10">
          <h4>Přehled odpovědí na problém "<?php echo($problem); ?>"</h4>
        <?php
           $pocet=count($answers);
           if (!$pocet) {
             ?>
            <div class="hlaska">Nejsou uloženy žádné odpovědi na problém "<?php echo($problem); ?>"<br /><a href="<?php echo("./?odpovedi=2&idp=".$this->post_get('idp')); ?>"><img src="icons/add.png" width="10" height="10" />Přidat odpověď</a></div>
             <?php
           } else {
           ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Odpovědi na problém "<?php echo($problem); ?>"</caption>
              <thead><tr><th>Název</th><th>Kognitivní schéma</th><th>Editace</th><th>Smazat</th></tr></thead>
              <tbody>
                <?php
                 foreach($answers as $answer) {
                ?>
                <tr>
                  <td><?php echo($answer['odpoved']); ?></td>
                  <td><strong><?php echo($answer['nazev']); ?></strong></td>
                  <td class="text-center"><?php echo("<a href=\"./?odpovedi=2&idp=".$this->post_get('idp')."&idks=".$answer['id_kog_schematu']."\">"); ?><img src="icons/pencil.png" width="16" height="16" /></a></td>
                  <td class="text-center"><?php echo("<a href=\"./?odpovedi=3&idp=".$this->post_get('idp')."&idks=".$answer['id_kog_schematu']."\">"); ?><img src="icons/bin_closed.png" width="16" height="16" /></a></td>
                </tr>
                   <?php } ?>
                <tr><td colspan="4"><a href="<?php echo("./?odpovedi=2&idp=".$this->post_get('idp')); ?>"><img src="icons/add.png" width="10" height="10" />Přidat odpověď</a></td>
           <?php } ?>
              </tbody>
            </table>
          </div>
        </div>
