        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Editace kognitivních schémat</h4>
          <form method="post" action="./">
            <input type="hidden" name="id" value="<?php echo($kschema['id']); ?>" />
            <div class="form-group">
              <label for="nazev">Název:</label>
              <input type="text" class="form-control" id="nazev" name="nazev" value="<?php echo($kschema['nazev']) ?>"/>
            </div>
            <button type="submit" class="btn btn-default" name="kschema">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
