    <td id="pravy_panel">
      <h4>Editace kognitivních schémat</h4>
      <form method="post" action="./">
        <input type="hidden" name="id" value="<?php echo($kschema['id']); ?>" />
        <table>
          <tr><td>Název:</td><td><input type="text" name="nazev" value="<?php echo($kschema['nazev']) ?>" size="85px" /></td></tr>
          <td colspan="2" align="center"><input type="submit" name="kschema" value="Uložit" /></td>
        </table>
      </form>
    </td><!-- /pravy_panel -->
