        <div class="col-sm-10">
          <h4>Přehled kognitivních schémat</h4>
          <?php
             $pocet = count($kschemas);
             if (!$pocet) {
          ?>
          <div class="hlaska">Nejsou uloženy žádné problémy</div>
          <?php
            } else {
          ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Problémy</caption>
              <thead><tr><th>Název</th><th class="text-center">Editace</th><th class="text-center">Smazat</th></tr></thead>
              <tbody>
            <?php
              foreach ($kschemas as $kschema) {
            ?> 
                <tr>
                  <td><?php echo($kschema['nazev']); ?></td>
                  <td class="text-center"><?php echo("<a href=\"./?kschema=2&id=".$kschema['id']."\">"); ?><img src="icons/pencil.png" width="16" height="16" /></a></td>
                  <td class="text-center"><?php echo("<a href=\"./?kschema=3&id=".$kschema['id']."\">"); ?><img src="icons/bin_closed.png" width="16" height="16" /></a></td>
                </tr>
        <?php } ?>
              </tbody>
            </table>
          </div>
      <?php } ?>
        </div><!-- /col-sm-10 -->
