      <td id="pravy_panel">
        <h4>Vložení nového problému</h4>
        <form method="post" action="./"><table>
          <tr><td>Název:</td><td><input type="text" name="nazev" size="85px" /></td></tr>
          <tr><td>Popis:</td><td><textarea name="popis" cols="100" rows="10" wrap="soft"></textarea></td></tr>
          <td colspan="2" align="center"><input type="submit" name="prob" value="Uložit" /></td>
        </table></form>
      </td><!-- /pravy_panel -->
