        <td id="pravy_panel">
        <h4>Přehled problémů</h4>
       <?php
            $pocet=count($problems);
            if (!$pocet) {
              ?><div style="font-size: 13px; font-weight: bold;">Nejsou uloženy žádné problémy</div><?php
            } else {
            ?>
          <table class="prehled">
            <tr><td colspan="5" class="hlavicka">Problémy</td></tr>
            <tr><th>Název</th><th>Popis</th><th>Editace</th><th>Odpovědi</th><th>Smazat</th></tr>
            <?php
              foreach ($problems as $problem) {
                if (!$problem['smazano']) {
                ?> <tr>
                    <td><?php echo($problem['nazev']); ?></td>
                    <td><?php echo($problem['popis']); ?></td>
                    <td class="center"><?php echo("<a href=\"./?prob=2&id=".$problem['id']."\">"); ?><img src="icons/pencil.png" width="16" height="16" /></a></td>
                    <td class="center"><?php echo("<a href=\"./?odpovedi=1&idp=".$problem['id']."\">"); ?><img src="icons/comment.png" width="16" height="16" /></a></td>
                    <td class="center"><?php echo("<a href=\"./?prob=3&id=".$problem['id']."\">"); ?><img src="icons/bin_closed.png" width="16" height="16" /></a></td>
                  </tr>
                <?php
                }
              }
            }
          ?>
          </table>
      </td><!-- /pravy_panel -->
