    <td id="pravy_panel">
      <h4>Editace problému</h4>
      <form method="post" action="./">
        <input type="hidden" name="id" value="<?php echo($problem['id']); ?>" />
        <table>
          <tr><td>Název:</td><td><input type="text" name="nazev" value="<?php echo($problem['nazev']) ?>" size="85px" /></td></tr>
          <tr><td>popis:</td><td><textarea name="popis" cols="100" rows="10" wrap="soft"><?php echo($problem['popis']) ?></textarea></td></tr>
          <td colspan="2" align="center"><input type="submit" name="prob" value="Uložit" /></td>
        </table>
      </form>
    </td><!-- /pravy_panel -->
