        <div class="col-sm-10">
          <h4>Přehled odpovědí na problém "<?php echo($problem['name']); ?>"</h4>
        <?php
           $num=count($answers);
           if (!$num) {
             ?>
            <div class="message">Nejsou uloženy žádné odpovědi na problém "<?php echo($problem['name']); ?>"<br /><a href="<?php echo("http://".$this->siteName."/administrator/answer-new/".$problem['id']); ?>"><img src="http://<?= $this->siteName ?>/administrator/icons/add.png" width="10" height="10" />Přidat odpověď</a></div>
             <?php
           } else {
           ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Odpovědi na problém "<?php echo($problem['name']); ?>"</caption>
              <thead><tr><th>Název</th><th>Kognitivní schéma</th><th class="text-center">Editace</th><th class="text-center">Smazat</th></tr></thead>
              <tbody>
                <?php
                 foreach($answers as $answer) {
                ?>
                <tr>
                  <td><?php echo($answer['answer']); ?></td>
                  <td><strong><?php echo($answer['name']); ?></strong></td>
                  <td class="text-center"><?php echo("<a href=\"http://".$this->siteName."/administrator/answer-edit/".$answer['id']."\">"); ?><img src="http://<?= $this->siteName ?>/administrator/icons/pencil.png" width="16" height="16" /></a></td>
                  <td class="text-center"><?php echo("<a href=\"http://".$this->siteName."/administrator/answer-delete/".$answer['id']."\">"); ?><img src="http://<?= $this->siteName ?>/administrator/icons/bin_closed.png" width="16" height="16" /></a></td>
                </tr>
                   <?php } ?>
                <tr><td colspan="4"><a href="<?php echo("http://".$this->siteName."/administrator/answer-new/".$answer['id_problem']); ?>"><img src="http://<?= $this->siteName ?>/administrator/icons/add.png" width="10" height="10" />Přidat odpověď</a></td>
              </tbody>
            </table>
           <?php } ?>
          </div>
        </div>
