        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Editace kognitivních schémat</h4>
          <form method="post" action="http://<?= $this->siteName ?>/administrator/c-schema-update">
            <input type="hidden" name="id" value="<?php echo($cschema['id']); ?>" />
            <div class="form-group">
              <label for="name">Název:</label>
              <input type="text" class="form-control" id="name" name="name" value="<?php echo($cschema['name']) ?>"/>
            </div>
            <button type="submit" class="btn btn-default" name="cschema" value="Uložit">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
