        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Vložení nového kognitivního schématu</h4>
          <form method="post" action="http://<?= $this->siteName ?>/administrator/c-schema-add">
            <div class="form-group">
              <label for="name">Název:</label>
              <input type="text" class="form-control" id="name" name="name">
            </div>
            <div class="form-group">
              <label for="lang">Jazyk:</label>
              <select class="form-control" id="lang" name="lang">
              <?php
                foreach($langs as $lang)
                {
                  echo("                  <option value=\"".$lang['id']."\" >[".$lang['text_id']."] ".$lang['name']."</option>\n");
                }
              ?>
            </select>
            </div>
            <div class="form-group">
              <label for="wrong">Chybná odpověď:</label>
              <input type="checkbox" id="wrong" name="wrong">
            </div>
            <button type="submit" class="btn btn-default" name="cschema" value="Save">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
