        <div class="col-sm-10">
          <h4>Přehled kognitivních schémat</h4>
          <?php
             $num = count($cschemas);
             if (!$num) {
          ?>
          <div class="message">Nejsou uložena žádná kognitivní schémata</div>
          <?php
            } else {
          ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Kognitivní schémata</caption>
              <thead><tr><th>Název</th><th class="text-center">Editace</th><th class="text-center">Smazat</th></tr></thead>
              <tbody>
            <?php
              foreach ($cschemas as $cschema) {
            ?> 
                <tr>
                  <td><?php echo($cschema['name']); ?></td>
                  <td class="text-center"><?php echo("<a href=\"http://".$this->siteName."/administrator/c-schema-edit/".$cschema['id']."\">"); ?><img src="http://<?= $this->siteName ?>/administrator/icons/pencil.png" width="16" height="16" /></a></td>
                  <td class="text-center"><?php echo("<a href=\"http://".$this->siteName."/administrator/c-schema-delete/".$cschema['id']."\">"); ?><img src="http://<?= $this->siteName ?>/administrator/icons/bin_closed.png" width="16" height="16" /></a></td>
                </tr>
        <?php } ?>
              </tbody>
            </table>
          </div>
      <?php } ?>
        </div><!-- /col-sm-10 -->
