        <div class="col-sm-10">
          <h4>Přehled Lektorů Studenta <?=$student['nick']?></h4>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Lektoři</caption>
              <thead><tr><th>Přezdívka</th><th class="text-center">Lektor studenta</th></tr></thead>
              <tbody><form method="post" action="http://<?= $this->siteName ?>/administrator/lectors-save">
              	<input type="hidden" name="ids" value="<?= $student['id'] ?>" />
                <?php
                  foreach ($lectors as $lector) {
                ?>
                <tr>
                  <td><?php echo($lector['nick']); ?></td>
                  <td class="text-center"><input type="checkbox" id="lector<?= $lector['id'] ?>" name="lector<?= $lector['id'] ?>" <?php if ($lector['student']) { echo("checked=\"checked\""); }; ?> /></td>
                </tr>
                <?php } ?>
                <tr><td><button type="submit" name="users" class="btn btn-default" value="Save">Uložit</button></td><td></td></tr>
              </form></tbody>
            </table>
          </div>
        </div><!-- /col-sm-10 -->

        
