        <div class="col-sm-4"></div>
        <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Přihlášení</div>
            <div class="panel-body">
              <form method="post" action="./login">
                <div class="form-group">
                  <label for="login_user">Uživatel:</label>
                  <input type="text" class="form-control" id="login_user" name="login_user">
                </div>
                <div class="form-group">
                  <label for="login_passw">heslo:</label>
                  <input type="password" class="form-control" id="login_passw" name="login_passw">
                </div>
                <button type="submit" class="btn btn-default" name="login" value="login">Přihlásit</button>
              </form>
            </div>
          </div>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-4"></div>
