        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Editace problému</h4>
          <form method="post" action="http://<?= $this->siteName ?>/administrator/problem-update">
            <input type="hidden" name="id" value="<?php echo($problem['id']); ?>" />
            <div class="form-group">
              <label for="name">Název:</label>
              <input type="text" class="form-control" id="name" name="name" value="<?php echo($problem['name']) ?>"/>
            </div>
            <div class="form-group">
              <label for="description">Popis:</label>
              <textarea class="form-control" rows="5" id="description" name="description"><?php echo($problem['description']) ?></textarea>
            </div>
            <button type="submit" name="prob" class="btn btn-default" value="Save">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
    
