        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Vložení nového problému</h4>
          <form method="post" action="http://<?= $this->siteName ?>/administrator/problem-add">
            <div class="form-group">
              <label for="nazev">Název:</label>
              <input type="text" class="form-control" id="nazev" name="nazev">
            </div>
            <div class="form-group">
              <label for="popis">Popis:</label>
              <textarea class="form-control" rows="5" id="popis" name="popis"></textarea>
            </div>
            <button type="submit" name="prob" class="btn btn-default" value="Uložit">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
