        <div class="col-sm-10">
          <h4>Přehled problémů</h4>
          <?php
            $num=count($problems);
            if (!$num) {
          ?>
          <div class="message">Nejsou uloženy žádné problémy</div>
          <?php
            } else {
          ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Problémy</caption>
              <thead><tr><th>Název</th><th>Popis</th><th>Jazyk</th><th class="text-center">Editace</th><th class="text-center">Řešení</th><th class="text-center">Smazat</th></tr></thead>
              <tbody>
            <?php
              foreach ($problems as $problem) {
                if (!$problem['deleted']) {
            ?>
                   <tr>
                    <td><?php echo($problem['name']); ?></td>
                    <td><?php echo($problem['description']); ?></td>
                    <td><?php echo($problem['lang']); ?></td>
                    <td class="text-center"><?php echo("<a href=\"<?= $this->protocol ?>://".$this->siteName."/administrator/problem-edit/".$problem['id']."\">"); ?><img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/pencil.png" width="16" height="16" /></a></td>
                    <td class="text-center"><?php echo("<a href=\"<?= $this->protocol ?>://".$this->siteName."/administrator/answer-overview/".$problem['id']."\">"); ?><img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/comment.png" width="16" height="16" /></a></td>
                    <td class="text-center"><?php echo("<a href=\"<?= $this->protocol ?>://".$this->siteName."/administrator/problem-delete/".$problem['id']."\">"); ?><img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/bin_closed.png" width="16" height="16" /></a></td>
                  </tr>
                <?php
                }
              } ?>
              </tbody>
            </table>
          </div>
      <?php }
          ?>
        </div><!-- /col-sm-10 -->

        
