        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Vložení nového problému</h4>
          <form method="post" action="<?= $this->protocol ?>://<?= $this->siteName ?>/administrator/problem-add">
            <div class="form-group">
              <label for="name">Název:</label>
              <input type="text" class="form-control" id="name" name="name">
            </div>
            <div class="form-group">
              <label for="lang">Jazyk:</label>
              <select class="form-control" id="lang" name="lang">
              <?php
                foreach($langs as $lang)
                {
                  echo("                  <option value=\"".$lang['id']."\" >[".$lang['text_id']."] ".$lang['name']."</option>\n");
                }
              ?>
            </select>
            </div>
            <div class="form-group">
              <label for="description">Popis:</label>
              <textarea class="form-control" rows="5" id="description" name="description"></textarea>
            </div>
            <button type="submit" name="prob" class="btn btn-default" value="Save">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
