        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Vložení nového uživatele</h4>
          <form method="post" action="http://<?= $this->siteName ?>/administrator/users-add/">
            <div class="form-group">
              <label for="nick"><span class="red">* </span>Přezdívka:</label>
              <input type="text" class="form-control" id="nick" name="nick"/>
            </div>
            <div class="form-group">
              <label for="jmeno">Jméno:</label>
              <input type="text" class="form-control" id="jmeno" name="jmeno"/>
            </div>
            <div class="form-group">
              <label for="prijmeni">Příjmení:</label>
              <input type="text" class="form-control" id="prijmeni" name="prijmeni"/>
            </div>
            <div class="form-group">
              <label for="heslo1"><span class="red">* </span>Heslo:</label>
              <input type="password" class="form-control" id="heslo1" name="heslo1"/>
            </div>
            <div class="form-group">
              <label for="heslo2"><span class="red">* </span>Heslo podruhé:</label>
              <input type="password" class="form-control" id="heslo2" name="heslo2"/>
            </div>
            <div class="form-group">
              <label for="prava"><span class="red">* </span>Admin:</label>
              <input type="checkbox" id="prava" name="prava"/>
            </div>
            <button type="submit" name="users" class="btn btn-default" value="Save">Uložit</button><label><span class="red">&nbsp;&nbsp;*&nbsp;</span>=&nbsp;Povinné údaje</label>
         </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
