        <div class="col-sm-10">
          <h4>Přehled problémů</h4>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Problémy</caption>
              <thead><tr><th>Přezdívka</th><th>Jméno</th><th class="text-center">Admin</th><th class="text-center">Editace</th><th class="text-center">Smazat</th></tr></thead>
              <tbody>
                <?php
                  foreach ($users as $user) {
                ?>
                <tr>
                  <td><?php echo($user['nick']); ?></td>
                  <td><?php echo($user['jmeno']." ".$user['prijmeni']); ?></td>
                  <td class="text-center"><?php if (($user['id']!=1)&&($user['id']!=$_SESSION['id_usera'])) {echo("<a href=\"http://".$this->siteName."/administrator/users-admin/".$user['id']."\">");}; ?><?php if ($user['prava']) { ?><img src="http://<?=$this->siteName?>/administrator/icons/accept.png"/><?php } else { ?><img src="http://<?=$this->siteName?>/administrator/icons/cross.png"/><?php }; if (($user['id']!=1)&&($user['id']!=$_SESSION['id_usera'])) { echo "</a>"; }; ?></td>
                  <td class="text-center"><?php echo("<a href=\"http://".$this->siteName."/administrator/users-edit/".$user['id']."\">"); ?><img src="http://<?=$this->siteName?>/administrator//icons/pencil.png" width="16" height="16" /></a></td>
                  <td class="text-center"><?php if (($user['id']!=1)&&($user['id']!=$_SESSION['id_usera'])) {echo("<a href=\"http://".$this->siteName."/administrator/users-delete/".$user['id']."\">");}; ?><img src="icons/bin_closed.png" /><?php if (($user['id']!=1)&&($user['id']!=$_SESSION['id_usera'])) { echo "</a>"; }; ?></td>
                </tr>
                <?php
              } ?>
              </tbody>
            </table>
          </div>
        </div><!-- /col-sm-10 -->

        
