        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Editace údajů uživatele</h4>
          <form method="post" action="<?= $this->protocol ?>://<?= $this->siteName ?>/administrator/users-update">
            <input type="hidden" name="id" value="<?= $user['id'] ?>" />
            <div class="form-group">
              <label for="nick"><span class="red">* </span>Přezdívka:</label>
              <input type="text" class="form-control" id="nick" name="nick" value="<?= $user['nick'] ?>" disabled="disabled" />
            </div>
            <div class="form-group">
              <label for="name">Jméno:</label>
              <input type="text" class="form-control" id="name" name="name" value="<?= $user['name'] ?>" />
            </div>
            <div class="form-group">
              <label for="surname">Příjmení:</label>
              <input type="text" class="form-control" id="surname" name="surname" value="<?= $user['surname'] ?>" />
            </div>
            <div class="form-group">
              <label for="password1"><span class="red">* </span>Původní heslo:</label>
              <input type="password" class="form-control" id="password1" name="password1"/>
            </div>
            <div class="form-group">
              <label for="password2"><span class="red">* </span>Nové heslo:</label>
              <input type="password" class="form-control" id="password2" name="password2"/>
            </div>
            <div class="form-group">
              <label for="password3"><span class="red">* </span>Nové heslo podruhé:</label>
              <input type="password" class="form-control" id="password3" name="password3"/>
            </div>
            <div class="form-group">
              <label for="permissions"><span class="red">* </span>Admin:</label>
              <input type="checkbox" id="permissions" name="permissions" <?php if ($user['permissions']) { echo("checked=\"checked\""); }; ?> disabled="disabled" />
            </div>
            <button type="submit" name="users" class="btn btn-default" value="Save">Save</button><label><span class="red">&nbsp;&nbsp;*&nbsp;</span>=&nbsp;Povinné údaje (Pokud nechcete měnit password, vstupní pole pro hesla nechte prázdná)</label>
         </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
