        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4>Vložení nové odpovědi na problém "<?php echo($problem['name']); ?>"</h4>
          <form method="post" action="http://<?= $this->siteName ?>/answer-add">
            <input type="hidden" name="idp" value="<?php echo($problem['id']); ?>" />
            <div class="form-group">
              <label for="idcs">Kognitivní schéma:</label>
              <select class="form-control" id="idcs" name="idcs">
              <?php
                foreach($cschemas as $cschema)
                {
                  echo("                  <option value=\"".$cschema['id']."\" >".$cschema['name']."</option>\n");
                }
              ?>
            </select>
            </div> 
            <div class="form-group">
              <label for="name">Odpověď:</label>
              <textarea class="form-control" rows="5" id="name" name="name"></textarea>
            </div>
            <button type="submit" name="answers" class="btn btn-default" value="Save">Save</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
