        <div class="col-sm-10">
          <h4>Přehled odpovědí na problém "<?= $problem['nazev'] ?>"</h4>
        <?php
           $pocet=count($answers);
           if (!$pocet) {
             ?>
            <div class="hlaska">Nejsou uloženy žádné odpovědi na problém "<?php echo($problem['nazev']); ?>"<br /><a href="<?php echo("http://".$this->siteName."/answer-new/".$problem['id']); ?>"><img src="http://<?= $this->siteName ?>/administrator/icons/add.png" width="10" height="10" />Přidat odpověď</a></div>
             <?php
           } else {
           ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <caption class="text-center">Odpovědi na problém "<?= $problem['nazev'] ?>"</caption>
              <thead><tr><th>Název</th><th>Kognitivní schéma</th></tr></thead>
              <tbody>
                <?php
                 foreach($answers as $answer) {
                ?>
                <tr>
                  <td><?php echo($answer['odpoved']); ?></td>
                  <td><strong><?php echo($answer['nazev']); ?></strong></td>
                </tr>
                   <?php } ?>
                <tr><td colspan="4"><a href="<?php echo("http://".$this->siteName."/answer-new/".$answer['id_problemu']); ?>"><img src="http://<?= $this->siteName ?>/administrator/icons/add.png" width="10" height="10" />Přidat odpověď</a></td>
              </tbody>
            </table>
           <?php } ?>
          </div>
        </div>
