<?php global $expressions, $lang; ?>        
        <div class="col-sm-10">
          <h4><?=$expressions['Solutions overview of the problem']?> "<?= $problem['name'] ?>"</h4>
        <?php
           $num=count($answers);
           if (!$num) {
             ?>
            <div class="message"><?=$expressions['There are not saved any solutions of the problem']?> "<?=$problem['name']?>"<br /><a href="http://<?=$this->siteName."/$lang"?>/answer-new/<?=$problem['id']?>"><img src="http://<?= $this->siteName ?>/administrator/icons/add.png" width="10" height="10" alt="add answer"/><?=$expressions['Add solution']?></a></div>
             <?php
           } else {
           ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr><th colspan="2" class="caption text-center"><?=$expressions['Solutions of the problem']?> "<?= $problem['name'] ?>"</th></tr>
                <tr><th><?=$expressions['Name']?></th><th><?=$expressions['Cognitive schema']?></th></tr>
              </thead>
              <tbody>
                <?php
                 foreach($answers as $answer) {
                ?>
                <tr>
                  <td><?=$answer['answer']?></td>
                  <td><strong><?=$answer['name']?></strong></td>
                </tr>
                   <?php } ?>
                <tr><td colspan="2"><a href="http://<?=$this->siteName."/$lang"?>/answer-new/<?=$problem['id']?>"><img src="http://<?= $this->siteName ?>/administrator/icons/add.png" width="10" height="10" alt="add answer" /><?=$expressions['Add solution']?></a></td>
              </tbody>
            </table>
           <?php } ?>
          </div>
        </div>
