<?php global $expressions, $lang; ?>        
        <div class="col-sm-10">
          <h4><?=$expressions['Cognitive schemas overview']?></h4>
          <?php
             $num = count($cschemas);
             if (!$num) {
          ?>
          <div class="message"><?=$expressions['There are not saved any cognitive schemas']?></div>
          <?php
            } else {
          ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr><th class="caption text-center"><?=$expressions['Cognitive schemas']?></th></tr>
                <tr><th><?=$expressions['Name']?></th></tr>
              </thead>
              <tbody>
            <?php
              foreach ($cschemas as $cschema) {
            ?> 
                <tr>
                  <td><?php echo($cschema['name']); ?></td>
                </tr>
        <?php } ?>
              </tbody>
            </table>
          </div>
      <?php } ?>
        </div><!-- /col-sm-10 -->
