        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Vložení nového kognitivního schématu</h4>
          <form method="post" action="http://<?= $this->siteName ?>/c-schema-add">
            <div class="form-group">
              <label for="name">Název:</label>
              <input type="text" class="form-control" id="name" name="name">
            </div>
            <button type="submit" name="cschema" value="Save">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
