        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <h4>Vložení nového kognitivního schématu</h4>
          <form method="post" action="http://<?= $this->siteName ?>/k-schema-add">
            <div class="form-group">
              <label for="nazev">Název:</label>
              <input type="text" class="form-control" id="nazev" name="nazev">
            </div>
            <button type="submit" class="btn btn-default" name="kschema" value="Uložit">Uložit</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
