        <div class="col-sm-10">
          <h4>Přehled kognitivních schémat</h4>
          <?php
             $pocet = count($kschemas);
             if (!$pocet) {
          ?>
          <div class="hlaska">Nejsou uloženy žádná kognitivní schémata</div>
          <?php
            } else {
          ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr><th class="caption text-center">Kognitivní schémata</th></tr>
                <tr><th>Název</th></tr>
              </thead>
              <tbody>
            <?php
              foreach ($kschemas as $kschema) {
            ?> 
                <tr>
                  <td><?php echo($kschema['nazev']); ?></td>
                </tr>
        <?php } ?>
              </tbody>
            </table>
          </div>
      <?php } ?>
        </div><!-- /col-sm-10 -->
