<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs-cz" lang="cs-cz">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="author" content="Softstar s.r.o.; mailto:softstar_cz@gmail.com"/>
    <meta name="copyright" content="Softstar s.r.o." />
    <title>Emotional stability learning - <?= $title ?></title>
    <meta name="description" content="Emotional stability learning" />
    <meta name="keywords" content="emotional stability, learning site" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://<?=$this->siteName?>/css/style.css" type="text/css" />
  </head>
  <body>
    <div class="container-fluid margintop30">
      <div id="header" class="shadow">
        <a href="http://<?=$this->siteName?>"><h1>Emotional Stability Learning</h1></a>
      </div>
      <div class="row">
        <div class="col-sm-2" >
          <ul class="list-group shadow" id="left_panel">
          <li class="list-group-item"><div class="category">
            <img src="http://<?=$this->siteName?>/administrator/icons/asterisk_orange.png" width="16" height="16" alt="icon" /> <span class="title">Projekt Emotional Stability Learning</span><br />
            <ul class="list-group">
              <li class="list-group-item"><a href="http://<?=$this->siteName?>/administrator/data/EmotionalStabilityLearning_projekt_cz.pdf">O projektu</a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="http://<?=$this->siteName?>/administrator/icons/application_side_list.png" width="16" height="16" alt="icon" /> <span class="title">Problémy</span><br />
            <ul class="list-group">
              <li class="list-group-item"><a href="http://<?=$this->siteName?>/problem-overview">Přehled problémů</a></li>
              <li class="list-group-item"><a href="http://<?=$this->siteName?>/problem-new">Přidat problém</a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="http://<?=$this->siteName?>/administrator/icons/blueprint.png" width="16" height="16" alt="icon" /> <span class="title">Kognitivní schémata</span><br/>
            <ul class="list-group">
              <li class="list-group-item"><a href="http://<?=$this->siteName?>/c-schema-overview">Přehled schémat</a></li>
              <li class="list-group-item"><a href="http://<?=$this->siteName?>/c-schema-new">Přidat schéma</a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="http://<?=$this->siteName?>/administrator/icons/lightbulb.png" width="16" height="16" alt="icon" /> <span class="title">Test</span><br/>
            <ul class="list-group">
              <li class="list-group-item"><a href="http://<?=$this->siteName?>/test">Otestovat se</a></li>
            </ul>
          </div></li>
          </ul>
        </div>
      <?php 
        $this->controller->showView(); // vložení aktuálního pohledu do šablony
      ?>
      </div>
      <div class="row"><div class="col-sm-12 margintop30">
        <div class="text-center shadow" id="footer">Copyright &copy; <?php date_default_timezone_set('Europe/Prague'); echo date("Y"); ?> <a href="http://www.softstar.cz">Softstar s.r.o.</a><br /><a href="http://validator.w3.org/check?uri=referer" title="" onclick="return !window.open(this.href);">XHTML</a> a <a href="http://jigsaw.w3.org/css-validator/check/referer" title="" onclick="return !window.open(this.href);">CSS 3.0</a></div>
      </div></div>
    </div><!-- /container -->
  </body>
</html>
