<!DOCTYPE html>
<html xmlns="<?= $this->protocol ?>://www.w3.org/1999/xhtml" xml:lang="cs-cz" lang="cs-cz">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="author" content="Softstar s.r.o.; mailto:softstar_cz@gmail.com"/>
    <meta name="copyright" content="Softstar s.r.o." />
    <title>Emotional stability learning - <?= $title ?></title>
    <meta name="description" content="Emotional stability learning" />
    <meta name="keywords" content="emotional stability, learning site" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?= $this->protocol ?>://<?=$this->siteName?>/css/style.css" type="text/css" />
  </head>
  <body>
    <div class="container-fluid margintop30">
      <div id="header" class="shadow">
        <a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>"><h1>Emotional Stability Learning</h1></a>
      </div>
      <div class="row">
        <div class="col-sm-2" >
          <ul class="list-group shadow" id="left_panel">
          <li class="list-group-item"><div class="category">
            <img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/asterisk_orange.png" width="16" height="16" alt="icon" /> <span class="title"><?=$expressions['Project']?> Emotional Stability Learning</span><br />
            <ul class="list-group">
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/data/EmotionalStabilityLearning_<?=$expressions['project']?>_<?=$lang?>.pdf"><?=$expressions['About project']?></a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/application_side_list.png" width="16" height="16" alt="icon" /> <span class="title"><?=$expressions['Problems']?></span><br />
            <ul class="list-group">
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/problem-overview"><?=$expressions['Problems overview']?></a></li>
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/problem-new"><?=$expressions['Add problem']?></a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/blueprint.png" width="16" height="16" alt="icon" /> <span class="title"><?=$expressions['Cognitive schemas']?></span><br/>
            <ul class="list-group">
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/c-schema-overview"><?=$expressions['Schemas overview']?></a></li>
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/c-schema-new"><?=$expressions['Add schema']?></a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/lightbulb.png" width="16" height="16" alt="icon" /> <span class="title"><?=$expressions['Learning']?></span><br/>
            <ul class="list-group">
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/learning"><?=$expressions['Learning']?></a></li>
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/test"><?=$expressions['Test yourselves']?></a></li>
            </ul>
          </div></li>
          <li class="list-group-item"><div class="category">
            <img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/icons/user.png" width="16" height="16" alt="icon" /> <span class="title"><?=$expressions['Users']?><?php if (!empty($_COOKIE['user_id'])) { ?>:<?php } ?></span><?php if (!empty($_COOKIE['user_id'])) { echo(' '.$fuser['nick']); } ?><br/>
            <ul class="list-group">
            <?php if (empty($_COOKIE['user_id'])) { ?>
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/login-view"><?=$expressions['Login']?></a></li>
              <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/registration-view"><?=$expressions['Registration']?></a></li>
            <?php } else { ?>
            <li class="list-group-item"><a href="<?= $this->protocol ?>://<?=$this->siteName?>/<?=$lang?>/logout"><?=$expressions['Logout']?></a></li>
            <?php } ?>
            </ul>
            <center>
                <a href="<?= $this->protocol ?>://<?=$this->siteName?>/cs" title="Čeština"><img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/lang_icons/cs.png" /></a>
                <a href="<?= $this->protocol ?>://<?=$this->siteName?>/en" title="English"><img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/lang_icons/en.png" /></a>
                <a href="<?= $this->protocol ?>://<?=$this->siteName?>/de" title="Deutsch"><img src="<?= $this->protocol ?>://<?=$this->siteName?>/administrator/lang_icons/de.png" /></a>
            </center>
          </div></li>
          </ul>
        </div>
      <?php 
        $this->controller->showView(); // vložení aktuálního pohledu do šablony
      ?>
      </div>
      <div class="row"><div class="col-sm-12 margintop30">
        <div class="text-center shadow" id="footer">Copyleft &copy; <?php date_default_timezone_set('Europe/Prague'); echo date("Y"); ?> <a href="<?= $this->protocol ?>://www.softstar.cz">Softstar s.r.o.</a><br /><a href="<?= $this->protocol ?>://validator.w3.org/check?uri=referer" title="" onclick="return !window.open(this.href);">XHTML</a> a <a href="<?= $this->protocol ?>://jigsaw.w3.org/css-validator/check/referer" title="" onclick="return !window.open(this.href);">CSS 3.0</a></div>
      </div></div>
    </div><!-- /container -->
  </body>
</html>
