<?php global $expressions, $lang; ?>        
        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4><?=$expressions['Learning']?></h4>
        <div class="message"><?=$expressions['Problem']?>: <?=$problem['name']?><br /><?php if ($cschema['id']<100) echo($expressions['Cognitive schema'].": $cschema[name]"); else echo($expressions['Solutions'].":"); ?></div><br /><br />
          <form method="post" action="http://<?= $this->siteName."/$lang" ?>/learning">
            <input type="hidden" name="idp" value="<?=$problem['id']?>" />
            <input type="hidden" name="idcs" value="<?=$cschema['id']?>" />
            <input type="hidden" name="problems" value="<?=$problems?>" />
            <div class="form-group">
              <?php
//                 print_r($answers);
                foreach($answers as $answer)
                {
                    if ($cschema['id'] < 100)
                    {
                        echo("                  <div class=\"testbox\"><span class=\"radiotext\">- $answer[answer]</span></div><br />\n");
                    }
                    else
                    {
                        if ($answer['id_cog_schema'] != 1) echo("                  <div class=\"testbox\"><span class=\"radiotext\"><strong>$answer[name_cog_schema]:</strong> $answer[answer]</span></div><br />\n");
                    }
                }
              ?>
            </div> 
            <button type="submit" name="test2" value="Continue"><?=$expressions['Next']?></button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
