        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4>Výuka</h4>
        <div class="message">Problém: <?=$problem['name']?>. <?php if ($cschema['id']<100) echo("Odpověď pro kognitivní schéma \"$cschema[name]\":"); else echo("Odpovědi:"); ?></div><br /><br />
          <form method="post" action="http://<?= $this->siteName ?>/learning">
            <input type="hidden" name="idp" value="<?=$problem['id']?>" />
            <input type="hidden" name="idcs" value="<?=$cschema['id']?>" />
            <div class="form-group">
              <?php
//                 print_r($answers);
                foreach($answers as $answer)
                {
                    echo("                  <div class=\"testbox\"><span class=\"radiotext\">- $answer[answer]</span></div><br />\n");
                }
              ?>
            </div> 
            <button type="submit" name="test2" value="Continue">Pokračovat</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
