<?php global $expressions, $lang; ?>        
        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4><?=$expressions['Learning']?></h4>
        <div class="message"><?=$expressions['Select learned cognitive schema. Solutions will correspond to this schema then.']?></div><br /><br />
          <form method="post" action="http://<?= $this->siteName."/$lang" ?>/learning">
            <div class="form-group">
              <label for="idcs"><?=$expressions['Cognitive schema']?>:</label><br /><br />
                <table id="schemas">
	                <tr><td><input type='radio' id="idcs" name='idcs' value="100" /></td><td> <?=$expressions['All schemas']?></td></tr>
              <?php
                foreach($cschemas as $cschema)
                {
                    if ($cschema['wrong'] != 1)
                        echo("                  <tr><td><input type='radio' id=\"idcs\" name='idcs' value=\"$cschema[id]\" class=\"radio\" /></td><td> $cschema[name]</td></tr>\n");
                }
              ?>
              </table>
            </div> 
            <button type="submit" name="test1" value="Continue"><?=$expressions['Next']?></button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
