<?php global $expressions, $lang; ?>        
        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4><?=$expressions['Learning']?></h4>
        <div class="message"><?=$expressions['Problem']?>: <?=$problem['name']?><br /><?php if ($cschema['id']<100) echo($expressions['Cognitive schema'].": $cschema[name]"); else echo($expressions['Solutions'].":"); ?></div><br /><br />
          <form method="post" action="<?= $this->protocol ?>://<?= $this->siteName."/$lang" ?>/learning">
            <input type="hidden" name="idp" value="<?=$problem['id']?>" />
            <input type="hidden" name="idcs" value="<?=$cschema['id']?>" />
            <div class="form-group">
            	<table id="schemas">
              <?php
//                 print_r($answers);
                foreach($answers as $answer)
                {
                    if ($cschema['id'] < 100)
                    {
                        echo("                  <tr><td><input type='radio' id=\"answer\" name=\"answer\" value=\"$answer[id]\" class=\"radio\" /></td><td> $answer[answer]</td></tr>\n");
                    }
                    else
                    {
                        echo("                  <tr><td><span class=\"radiotext\"><strong>$answer[name_cog_schema]:</strong> $answer[answer]</span></td></tr>\n");
                    }
                }
                if ($cschema['id'] < 100) echo("                   <tr><td><input type='radio' id=\"answer\" name='answer' value=\"-1\" class=\"radio\" /></td><td> ".$expressions['I can solve this']."</td></tr>\n");
              ?>
              </table>
            </div> 
            <button type="submit" name="learning" value="Continue"><?=$expressions['Next']?></button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
