        <div class="col-sm-10">
          <h4>Přehled problémů</h4>
          <?php
            $number=count($problems);
            if (!$number) {
          ?>
          <div class="hlaska">Nejsou uloženy žádné problémy</div>
          <?php
            } else {
          ?>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr><th colspan="3" class="caption text-center">Problémy</th></tr>
                <tr><th>Název</th><th>Popis</th><th class="text-center">Odpovědi</th></tr>
              </thead>
              <tbody>
            <?php
              foreach ($problems as $problem) {
                if (!$problem['deleted']) {
            ?>
                   <tr>
                    <td><?php echo($problem['name']); ?></td>
                    <td><?php echo($problem['description']); ?></td>
                    <td class="text-center"><?php echo("<a href=\"http://".$this->siteName."/answer-overview/".$problem['id']."\">"); ?><img src="http://<?=$this->siteName?>/administrator/icons/comment.png" width="16" height="16" alt="answers"/></a></td>
                    </tr>
                <?php
                }
              } ?>
              </tbody>
            </table>
          </div>
      <?php }
          ?>
        </div><!-- /col-sm-10 -->

        
