<?php global $expressions, $lang; ?>
        <div class="col-sm-3"></div>
        <div class="col-sm-4">
          <div class="panel">
            <div class="panel-heading"><?=$expressions['Registration']?></div>
            <div class="panel-body">
              <form method="post" action="<?= $this->protocol ?>://<?= $this->siteName."/$lang" ?>/registration">
                <div class="form-group">
                  <label for="nick"><?=$expressions['Nick']?>:</label>
                  <input type="text" class="form-control" id="nick" name="nick">
                </div>
                <div class="form-group">
                  <label for="email"><?=$expressions['Email']?>:</label>
                  <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- div class="form-group">
                  <label for="student"><?=$expressions['Student']?>:</label>
                  <input type="checkbox" id="student" name="student" checked="checked">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </div>
                <div class="form-group">
                  <label for="lector"><?=$expressions['Lector']?>:</label>
                  <input type="checkbox" id="lector" name="lector">
                </div -->
                <div class="form-group">
                  <label for="password"><?=$expressions['Password']?>:</label>
                  <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="form-group">
                  <label for="password1"><?=$expressions['Password again']?>:</label>
                  <input type="password" class="form-control" id="password1" name="password1">
                </div>
                <div class="form-group">
                  <label for="gdpr"><?=$expressions['I agree with storing data in accordance with GDPR']?></label>
                  <input type="checkbox" id="gdpr" name="gdpr" class="checkbox" >
                </div>
                <button type="submit" name="login" value="login"><?=$expressions['Save']?></button>
              </form>
            </div>
          </div>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
