        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4>Test</h4>
        <div class="message">Problem: <?=$problem['name']?>. Vyberte jednu z odpovědí:</div><br /><br />
          <form method="post" action="http://<?= $this->siteName ?>/test">
            <input type="hidden" name="idp" value="<?=$problem['id']?>" />
            <input type="hidden" name="idcs" value="<?=$idcs?>" />
            <input type="hidden" name="nWrong" value="<?=$nWrong?>" />
            <input type="hidden" name="nCorrect" value="<?=$nCorrect?>" />
            <div class="form-group">
              <?php
                foreach($answers as $answer)
                {
                    echo("                  <input type='radio' name='answerCS' value=\"$answer[id_cog_schema]\"  class=\"inline\" /> $answer[answer]<br />\n");
                }
              ?>
            </div> 
            <button type="submit" name="test2" value="Continue">Pokračovat</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
