<?php global $expressions, $lang; ?>        
        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4>Test</h4>
        <div class="message"><?=$expressions['Problem']?>: <?=$problem['name']?><br /><?=$expressions['Cognitive schema']?>: <?=$cschema['name']?></div><br /><br />
          <form method="post" action="<?= $this->protocol ?>://<?= $this->siteName."/$lang" ?>/test">
            <input type="hidden" name="idp" value="<?=$problem['id']?>" />
            <input type="hidden" name="idcs" value="<?=$cschema['id']?>" />
            <input type="hidden" name="nWrong" value="<?=$nWrong?>" />
            <input type="hidden" name="nCorrect" value="<?=$nCorrect?>" />
            <div class="form-group">
              <?php
                foreach($answers as $answer)
                {
                    echo("                  <div class=\"testbox\"><input type='radio' name='answerCS' value=\"$answer[id_cog_schema]\"  class=\"radio\" />  <span class=\"radiotext\">$answer[answer]</span></div><br />\n");
                }
              ?>
            </div> 
            <button type="submit" name="test2" value="Continue"><?=$expressions['Next']?></button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
