        <div class="col-sm-3"></div>
        <div class="col-sm-4">
        <h4>Test</h4>
        <div class="message">Vyberte si testované kognitivní schéma. Vybrané odpovědi pak musí odpovídat tomuto schématu.</div><br /><br />
          <form method="post" action="http://<?= $this->siteName ?>/test">
            <div class="form-group">
              <label for="idcs">Kognitivní schéma:</label><br />
              <?php
                foreach($cschemas as $cschema)
                {
                    if ($cschema['id'] != 1)
                        echo("                  <input type='radio' id=\"idcs\" name='idcs' value=\"".$cschema['id']."\" > ".$cschema['name']."<br />\n");
                }
              ?>
            </div> 
            <button type="submit" name="test1" value="Continue">Pokračovat</button>
          </form>
        </div><!-- /col-sm-4 -->
        <div class="col-sm-3"></div>
