        <div class="col-sm-10">
        	<h4><?=$expressions['Interpretation videos']?></h4>
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems I - Emotions']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/lvE2eigJ03o">
            	</iframe> 
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems II - Plasticity of neurons']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/4keLQ7_0EOA">
            	</iframe> 
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems III - Mathematical description of problems']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/0t7pNSlzkTM">
            	</iframe> 
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems IV - Subjectivity principle']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/0CACGwnqi6A">
            	</iframe> 
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems V - Emotional disorders']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/dgA9O6c0QMU">
            	</iframe> 
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems VI - Practical demonstration']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/Uu0wKCW-OmU">
            	</iframe> 
        		<br /><br />
          		<h5><?=$expressions['Subjectivity of problems VII - Mental health project']?></h5>
            	<iframe width="720" height="405"  allowfullscreen
 	           		src="https://www.youtube.com/embed/2fFhf8dGeFk">
            	</iframe> 
        </div><!-- /col-sm-10 -->
          